import mongoose from 'mongoose';
import { EventPlan } from '../models/EventPlan.js';

export const generateAndSavePlan = async (req, res) => {
  return res.status(200).json({
    success: true,
    message: 'Plans are auto-generated by the chat agent. Use the chat to create an event plan.',
  });
};

export const listPlans = async (req, res) => {
  const userId = req.session.userId;
  const plans = await EventPlan.find({ userId })
    .sort({ createdAt: -1 })
    .limit(20)
    .select('planText eventDraftSnapshot createdAt')
    .lean();

  res.json({
    success: true,
    data: {
      plans: plans.map((p) => ({
        id: String(p._id),
        createdAt: p.createdAt,
        summary: p.eventDraftSnapshot
          ? `${p.eventDraftSnapshot.event_type || 'Event'} in ${p.eventDraftSnapshot.city || ''} for ${p.eventDraftSnapshot.guests || '?'} guests`
          : p.planText?.slice(0, 80) || 'Saved Plan',
        planText: p.planText,
      })),
    },
  });
};

export const getPlanById = async (req, res) => {
  const { id } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ success: false, message: 'Invalid plan id' });
  }

  const userId = req.session.userId;
  const doc = await EventPlan.findOne({ _id: id, userId }).lean();

  let resolvedDoc = doc;
  let fallbackUsed = false;
  if (!resolvedDoc) {
    resolvedDoc = await EventPlan.findOne({ userId })
      .sort({ createdAt: -1 })
      .lean();
    fallbackUsed = Boolean(resolvedDoc);
  }

  if (!resolvedDoc) {
    return res.status(404).json({ success: false, message: 'Plan not found' });
  }

  res.json({
    success: true,
    data: {
      plan: {
        id: String(resolvedDoc._id),
        planText: resolvedDoc.planText,
        eventPlan: resolvedDoc.eventPlan,
        eventDraftSnapshot: resolvedDoc.eventDraftSnapshot,
        vendorShortlist: resolvedDoc.vendorShortlist,
        createdAt: resolvedDoc.createdAt,
        fallbackUsed,
        requestedId: String(id),
      },
    },
  });
};

export const deletePlan = async (req, res) => {
  const { id } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ success: false, message: 'Invalid plan id' });
  }

  const result = await EventPlan.deleteOne({ _id: id, userId: req.session.userId });
  if (result.deletedCount === 0) {
    return res.status(404).json({ success: false, message: 'Plan not found' });
  }

  res.json({ success: true, message: 'Plan deleted' });
};
